---
name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.session }} / ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
        - {session: '', python-version: '3.9', os: ubuntu-latest}
        - {session: tests, python-version: '3.8', os: ubuntu-latest}
        - {session: tests, python-version: '3.10', os: ubuntu-latest}
        - {session: tests, python-version: '3.11', os: ubuntu-latest}
        - {session: tests, python-version: '3.8', os: macos-latest}
        - {session: tests, python-version: '3.9', os: macos-latest}

    env:
      NOXSESSION: ${{ matrix.session }}

    steps:
    - uses: actions/checkout@v4.1.0
      with:
        submodules: true
        ssh-key: ${{ secrets.AMAZON_REVIEWS_TESTDATA_DEPLOY_KEY }}
    - uses: actions/setup-python@v4.6.1
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --constraint=.github/constraints.txt pip poetry nox nox-poetry
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    - uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: latest
    - run: nox --python=${{ matrix.python-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
